import { GameProject } from "./types";

// Mock thumbnail URLs (using placeholder images)
const mockThumbnails = [
  "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop",
  "https://images.unsplash.com/photo-1556438064-2d7646166914?w=400&h=300&fit=crop",
  "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=400&h=300&fit=crop",
  "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&fit=crop",
  "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
  "https://images.unsplash.com/photo-1556438064-2d7646166914?w=400&h=300&fit=crop",
  "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop",
  "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?w=400&h=300&fit=crop",
  "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&fit=crop",
  "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
  "https://images.unsplash.com/photo-1556438064-2d7646166914?w=400&h=300&fit=crop",
  "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=300&fit=crop",
];

// Mock video URLs (using placeholder videos)
const mockVideos = [
  "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_1mb.mp4",
  "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_2mb.mp4",
  "https://sample-videos.com/zip/10/mp4/SampleVideo_1280x720_5mb.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
  "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
];

export const mockProjects: GameProject[] = [
  {
    _id: "1",
    creatorId: "current_user",
    title: "Space Adventure RPG",
    shortDescription:
      "An epic space exploration RPG with procedurally generated planets and deep character customization.",
    projectType: "idea_sale",
    status: "published",
    ideaSaleData: {
      description:
        "A revolutionary space RPG that combines exploration, combat, and storytelling. Players can discover new planets, build relationships with alien species, and make choices that affect the galaxy. Features include procedurally generated worlds, deep character progression, and a branching narrative system.",
      videoUrl: mockVideos[0],
      prototypeImages: [
        mockThumbnails[0],
        mockThumbnails[1],
        mockThumbnails[2],
      ],
      askingPrice: 15000,
      gameGenre: "RPG",
      targetPlatform: "PC",
      tags: ["space", "rpg", "exploration", "procedural", "narrative"],
    },
    thumbnail: mockThumbnails[0],
    viewCount: 1250,
    likeCount: 89,
    likedBy: ["user1", "user2", "user3"],
    publishedAt: new Date("2024-01-15"),
    isFeatured: true,
    searchKeywords: ["space", "rpg", "adventure", "exploration"],
    attachments: ["concept_art.zip", "game_design_doc.pdf"],
    averageRating: 4.5,
    reviewCount: 23,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    _id: "2",
    creatorId: "dev2",
    title: "Puzzle Quest Mobile",
    shortDescription:
      "A mobile puzzle game with unique mechanics and beautiful hand-drawn artwork.",
    projectType: "product_sale",
    status: "published",
    productSaleData: {
      description:
        "A complete mobile puzzle game built with Unity. Features 50+ levels, unique puzzle mechanics, beautiful hand-drawn artwork, and smooth touch controls. The game includes a level editor, achievements system, and social features.",
      codeFolderPath: "/projects/puzzle_quest_mobile",
      screenshots: [
        mockThumbnails[3],
        mockThumbnails[4],
        mockThumbnails[5],
        mockThumbnails[6],
      ],
      demoUrl: "https://puzzlequest-demo.com",
      askingPrice: 8000,
      gameGenre: "Puzzle",
      targetPlatform: "Mobile",
      tags: ["puzzle", "mobile", "unity", "hand-drawn", "casual"],
      techStack: "Unity, C#, Android/iOS",
      isPlayable: true,
    },
    thumbnail: mockThumbnails[3],
    viewCount: 890,
    likeCount: 67,
    likedBy: ["user4", "user5", "user6", "user7"],
    publishedAt: new Date("2024-01-20"),
    isFeatured: false,
    searchKeywords: ["puzzle", "mobile", "unity", "casual"],
    attachments: ["source_code.zip", "assets.zip", "documentation.pdf"],
    averageRating: 4.2,
    reviewCount: 15,
    createdAt: new Date("2024-01-18"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    _id: "3",
    creatorId: "dev3",
    title: "Indie Horror Game Collaboration",
    shortDescription:
      "Looking for a publisher to collaborate on a psychological horror game with unique art style.",
    projectType: "dev_collaboration",
    status: "published",
    creatorCollaborationData: {
      description:
        "A psychological horror game that explores themes of isolation and fear through innovative gameplay mechanics. The game features a unique art style combining 2D and 3D elements, atmospheric sound design, and branching storylines.",
      proposal:
        "We're seeking a publisher who can provide marketing support, additional funding for polish, and help with distribution. Our team has 5 years of experience in indie game development and has previously released 2 successful titles.",
      budget: 25000,
      timeline: "6-8 months",
      prototypeImages: [
        mockThumbnails[7],
        mockThumbnails[8],
        mockThumbnails[9],
      ],
      videoUrl: mockVideos[1],
      gameGenre: "Horror",
      targetPlatform: "PC, Console",
      tags: ["horror", "psychological", "indie", "2d", "3d", "atmospheric"],
      skills: [
        "Game Design",
        "Programming",
        "Art Direction",
        "Sound Design",
        "Narrative Design",
      ],
    },
    thumbnail: mockThumbnails[7],
    viewCount: 567,
    likeCount: 34,
    likedBy: ["user8", "user9"],
    publishedAt: new Date("2024-01-25"),
    isFeatured: true,
    searchKeywords: ["horror", "collaboration", "indie", "psychological"],
    attachments: [
      "prototype_build.zip",
      "pitch_deck.pdf",
      "team_portfolio.pdf",
    ],
    averageRating: 4.8,
    reviewCount: 8,
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    _id: "4",
    creatorId: "current_user",
    title: "Retro Arcade Shooter",
    shortDescription:
      "A fast-paced retro-style arcade shooter with modern twists and online multiplayer.",
    projectType: "idea_sale",
    status: "draft",
    ideaSaleData: {
      description:
        "A modern take on classic arcade shooters with pixel art graphics, intense gameplay, and online multiplayer modes. Features include power-ups, boss battles, leaderboards, and both local and online co-op modes.",
      prototypeImages: [mockThumbnails[10], mockThumbnails[11]],
      askingPrice: 5000,
      gameGenre: "Arcade",
      targetPlatform: "PC, Console",
      tags: ["retro", "arcade", "shooter", "pixel-art", "multiplayer", "co-op"],
    },
    thumbnail: mockThumbnails[10],
    viewCount: 0,
    likeCount: 0,
    likedBy: [],
    isFeatured: false,
    searchKeywords: ["retro", "arcade", "shooter", "pixel"],
    attachments: [],
    averageRating: 0,
    reviewCount: 0,
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-01-28"),
  },
  // Additional projects for pagination testing
  {
    _id: "5",
    creatorId: "dev5",
    title: "Fantasy MMORPG",
    shortDescription:
      "A massive multiplayer online RPG set in a rich fantasy world with player-driven economy.",
    projectType: "idea_sale",
    status: "published",
    ideaSaleData: {
      description:
        "An ambitious MMORPG featuring a persistent world, player housing, crafting systems, and epic raids. The game emphasizes social interaction and community building with guild systems and player-run events.",
      videoUrl: mockVideos[2],
      prototypeImages: [mockThumbnails[0], mockThumbnails[1]],
      askingPrice: 50000,
      gameGenre: "MMORPG",
      targetPlatform: "PC",
      tags: ["mmorpg", "fantasy", "multiplayer", "social", "crafting"],
    },
    thumbnail: mockThumbnails[0],
    viewCount: 2100,
    likeCount: 156,
    likedBy: ["user10", "user11", "user12"],
    publishedAt: new Date("2024-01-30"),
    isFeatured: true,
    searchKeywords: ["mmorpg", "fantasy", "multiplayer"],
    attachments: ["design_doc.pdf", "concept_art.zip"],
    averageRating: 4.7,
    reviewCount: 45,
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-30"),
  },
  {
    _id: "6",
    creatorId: "dev6",
    title: "Racing Simulator Pro",
    shortDescription:
      "A realistic racing simulator with authentic physics and licensed cars.",
    projectType: "product_sale",
    status: "published",
    productSaleData: {
      description:
        "A complete racing simulator built with Unreal Engine. Features realistic physics, 50+ licensed cars, multiple tracks, and VR support. Includes career mode, multiplayer racing, and extensive customization options.",
      codeFolderPath: "/projects/racing_simulator_pro",
      screenshots: [mockThumbnails[2], mockThumbnails[3], mockThumbnails[4]],
      demoUrl: "https://racing-sim-demo.com",
      askingPrice: 25000,
      gameGenre: "Racing",
      targetPlatform: "PC, Console",
      tags: ["racing", "simulator", "realistic", "vr", "multiplayer"],
      techStack: "Unreal Engine, C++, VR SDK",
      isPlayable: true,
    },
    thumbnail: mockThumbnails[2],
    viewCount: 1450,
    likeCount: 98,
    likedBy: ["user13", "user14"],
    publishedAt: new Date("2024-02-01"),
    isFeatured: false,
    searchKeywords: ["racing", "simulator", "realistic"],
    attachments: ["source_code.zip", "assets.zip"],
    averageRating: 4.4,
    reviewCount: 32,
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-02-01"),
  },
  {
    _id: "7",
    creatorId: "current_user",
    title: "City Builder Strategy",
    shortDescription:
      "A strategic city building game with resource management and diplomacy.",
    projectType: "idea_sale",
    status: "draft",
    ideaSaleData: {
      description:
        "A complex city builder that combines resource management, diplomacy, and strategic planning. Players must balance economic growth with environmental concerns while managing relationships with neighboring cities.",
      prototypeImages: [mockThumbnails[5], mockThumbnails[6]],
      askingPrice: 12000,
      gameGenre: "Strategy",
      targetPlatform: "PC",
      tags: ["strategy", "city-builder", "resource-management", "diplomacy"],
    },
    thumbnail: mockThumbnails[5],
    viewCount: 0,
    likeCount: 0,
    likedBy: [],
    isFeatured: false,
    searchKeywords: ["strategy", "city-builder", "management"],
    attachments: [],
    averageRating: 0,
    reviewCount: 0,
    createdAt: new Date("2024-02-02"),
    updatedAt: new Date("2024-02-02"),
  },
  {
    _id: "8",
    creatorId: "dev8",
    title: "Indie Platformer Adventure",
    shortDescription:
      "A charming 2D platformer with hand-drawn art and engaging story.",
    projectType: "product_sale",
    status: "published",
    productSaleData: {
      description:
        "A complete 2D platformer featuring hand-drawn artwork, smooth animations, and an engaging story. Includes 30+ levels, collectibles, achievements, and multiple difficulty settings.",
      codeFolderPath: "/projects/platformer_adventure",
      screenshots: [mockThumbnails[7], mockThumbnails[8], mockThumbnails[9]],
      demoUrl: "https://platformer-demo.com",
      askingPrice: 6000,
      gameGenre: "Platformer",
      targetPlatform: "PC, Mobile",
      tags: ["platformer", "2d", "hand-drawn", "adventure", "indie"],
      techStack: "Unity, C#, 2D Toolkit",
      isPlayable: true,
    },
    thumbnail: mockThumbnails[7],
    viewCount: 780,
    likeCount: 45,
    likedBy: ["user15", "user16", "user17"],
    publishedAt: new Date("2024-02-03"),
    isFeatured: false,
    searchKeywords: ["platformer", "2d", "adventure"],
    attachments: ["source_code.zip", "art_assets.zip"],
    averageRating: 4.1,
    reviewCount: 18,
    createdAt: new Date("2024-01-30"),
    updatedAt: new Date("2024-02-03"),
  },
  {
    _id: "9",
    creatorId: "dev9",
    title: "VR Fitness Game",
    shortDescription:
      "An immersive VR fitness game that makes exercise fun and engaging.",
    projectType: "dev_collaboration",
    status: "published",
    creatorCollaborationData: {
      description:
        "A VR fitness game that combines exercise with gaming elements. Features multiple workout modes, progress tracking, and social features. Designed to make fitness accessible and enjoyable for all ages.",
      proposal:
        "We need a publisher with VR market experience and fitness industry connections. Our team has expertise in VR development and game design, but we need help with marketing and distribution.",
      budget: 35000,
      timeline: "8-10 months",
      prototypeImages: [mockThumbnails[10], mockThumbnails[11]],
      videoUrl: mockVideos[3],
      gameGenre: "Fitness",
      targetPlatform: "VR",
      tags: ["vr", "fitness", "health", "exercise", "social"],
      skills: [
        "VR Development",
        "Game Design",
        "Fitness Programming",
        "UI/UX Design",
      ],
    },
    thumbnail: mockThumbnails[10],
    viewCount: 420,
    likeCount: 28,
    likedBy: ["user18", "user19"],
    publishedAt: new Date("2024-02-04"),
    isFeatured: true,
    searchKeywords: ["vr", "fitness", "health"],
    attachments: ["prototype_vr_build.zip", "market_research.pdf"],
    averageRating: 4.6,
    reviewCount: 12,
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-04"),
  },
  {
    _id: "10",
    creatorId: "dev10",
    title: "Battle Royale Mobile",
    shortDescription:
      "A fast-paced battle royale game optimized for mobile devices.",
    projectType: "idea_sale",
    status: "published",
    ideaSaleData: {
      description:
        "A mobile-optimized battle royale game with 50-player matches, unique weapons, and dynamic environments. Features include cross-platform play, seasonal events, and a robust progression system.",
      videoUrl: mockVideos[4],
      prototypeImages: [
        mockThumbnails[0],
        mockThumbnails[1],
        mockThumbnails[2],
      ],
      askingPrice: 30000,
      gameGenre: "Battle Royale",
      targetPlatform: "Mobile",
      tags: ["battle-royale", "mobile", "multiplayer", "competitive"],
    },
    thumbnail: mockThumbnails[0],
    viewCount: 3200,
    likeCount: 234,
    likedBy: ["user20", "user21", "user22", "user23"],
    publishedAt: new Date("2024-02-05"),
    isFeatured: true,
    searchKeywords: ["battle-royale", "mobile", "competitive"],
    attachments: ["game_design_doc.pdf", "prototype_build.zip"],
    averageRating: 4.3,
    reviewCount: 67,
    createdAt: new Date("2024-01-29"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    _id: "11",
    creatorId: "dev11",
    title: "Educational Math Game",
    shortDescription:
      "A fun educational game that teaches math concepts through gameplay.",
    projectType: "product_sale",
    status: "published",
    productSaleData: {
      description:
        "An educational game designed to make math learning fun and engaging. Features adaptive difficulty, progress tracking, and curriculum alignment. Suitable for children aged 6-12.",
      codeFolderPath: "/projects/math_educational_game",
      screenshots: [mockThumbnails[3], mockThumbnails[4], mockThumbnails[5]],
      demoUrl: "https://math-game-demo.com",
      askingPrice: 8000,
      gameGenre: "Educational",
      targetPlatform: "Mobile, PC",
      tags: ["educational", "math", "children", "learning", "adaptive"],
      techStack: "Unity, C#, Educational APIs",
      isPlayable: true,
    },
    thumbnail: mockThumbnails[3],
    viewCount: 650,
    likeCount: 38,
    likedBy: ["user24", "user25"],
    publishedAt: new Date("2024-02-06"),
    isFeatured: false,
    searchKeywords: ["educational", "math", "children"],
    attachments: ["source_code.zip", "curriculum_docs.zip"],
    averageRating: 4.0,
    reviewCount: 15,
    createdAt: new Date("2024-02-02"),
    updatedAt: new Date("2024-02-06"),
  },
  {
    _id: "12",
    creatorId: "current_user",
    title: "Stealth Action Game",
    shortDescription:
      "A stealth-based action game with innovative mechanics and rich narrative.",
    projectType: "idea_sale",
    status: "draft",
    ideaSaleData: {
      description:
        "A stealth action game that emphasizes player choice and consequence. Features multiple approaches to objectives, dynamic AI, and a branching narrative that adapts to player decisions.",
      prototypeImages: [mockThumbnails[6], mockThumbnails[7]],
      askingPrice: 18000,
      gameGenre: "Stealth",
      targetPlatform: "PC, Console",
      tags: ["stealth", "action", "narrative", "choice", "ai"],
    },
    thumbnail: mockThumbnails[6],
    viewCount: 0,
    likeCount: 0,
    likedBy: [],
    isFeatured: false,
    searchKeywords: ["stealth", "action", "narrative"],
    attachments: [],
    averageRating: 0,
    reviewCount: 0,
    createdAt: new Date("2024-02-07"),
    updatedAt: new Date("2024-02-07"),
  },
];

export const mockStats = {
  totalProjects: 12,
  publishedProjects: 9,
  soldProjects: 0,
  totalRevenue: 0,
  averageRating: 4.3,
  totalViews: 15000,
  totalLikes: 1200,
};

export const mockDeveloperStats = {
  totalProjects: 4,
  publishedProjects: 1,
  soldProjects: 0,
  totalRevenue: 0,
  draftProjects: 3,
  inCollaborationProjects: 0,
  completedProjects: 0,
  totalViews: 1250,
  totalLikes: 89,
  averageRating: 4.5,
};

export const mockPublisherStats = {
  totalPurchasedProjects: 0,
  totalSpent: 0,
  activeCollaborations: 0,
  completedCollaborations: 0,
  favoriteGenres: ["RPG", "Puzzle", "Horror"],
  averagePurchasePrice: 0,
};
